baseURL = 'https://warpedvisions.org/'
languageCode = 'en-us'
title = 'warpedvisions.org'
theme = 'w42'

buildDrafts = true
disableLiveReload = true

[params]
description = '[ESSAYS](/), [RECIPES](/food), AND [GENERAL MAKERY](/projects) BY [BRUCE ALDERSON](/pages/about-bruce-alderson).'
footer.text = "[@robotpony.bsky.social](https://bsky.app/profile/robotpony.bsky.social)"
disableSpecial1stPost = true
defaultTheme = "light"

warpedScript = "https://cdn.warpedvisions.org/warped.js"
warpedStyle = "https://cdn.warpedvisions.org/warped.css"

# newContentEditor = "ia"

[cover]
hidden = false 
hiddenInList = false
hiddenInSingle = false 

[security]
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^vim$']

[services]
[services.googleAnalytics]
id = "G-77V9MKYGJ8"

[params.assets]
disableScrollBarStyle = true

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = false
noHl = false
style = 'monokai'
tabWidth = 4

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

